
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class Giaovien_Xoa_Sua extends javax.swing.JPanel {

    public static Dimension size;
    DefaultListModel model = new DefaultListModel();
    JList list = new JList(model);

    public String MALOPHOC;
    public String MAMH = "";

    public Giaovien_Xoa_Sua() throws SQLException {
        this.MALOPHOC = "";
        initComponents();
        String[] a = Giaovien.getDsLop(main.Maso);
        for (int i = 0; i < a.length; i++) {
            model.add(i, a[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MSSV = new javax.swing.JTextField();
        btSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMon = new javax.swing.JList(model);
        TENMH = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txTen = new javax.swing.JLabel();
        txMSSV = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txLop = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txQT = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txGK = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txCK = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txHP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập MSSV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UTM Amerika Sans", 1, 18), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("MSSV: ");

        MSSV.setFont(new java.awt.Font("UTM Times", 0, 18)); // NOI18N
        MSSV.setText("16520000");
        MSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSSVActionPerformed(evt);
            }
        });
        MSSV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MSSVKeyPressed(evt);
            }
        });

        btSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSubmit.setText("Tìm kiếm");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        listMon.setBackground(new java.awt.Color(0, 51, 51));
        listMon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        listMon.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        listMon.setForeground(new java.awt.Color(255, 255, 51));
        listMon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMon.setValueIsAdjusting(true);
        listMon.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMonValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMon);

        TENMH.setFont(new java.awt.Font("UTM Amerika Sans", 1, 24)); // NOI18N
        TENMH.setForeground(new java.awt.Color(255, 255, 51));
        TENMH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TENMH.setText("Chọn lớp học...");
        TENMH.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Danh sách mã lớp học:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sinh viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("UTM Amerika Sans", 1, 18), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel3.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("+ Họ tên: ");

        txTen.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txTen.setForeground(new java.awt.Color(255, 255, 51));

        txMSSV.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txMSSV.setForeground(new java.awt.Color(255, 255, 51));

        jLabel6.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("+ MSSV: ");

        txLop.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txLop.setForeground(new java.awt.Color(255, 255, 51));

        jLabel8.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("+ Lớp SH: ");

        jLabel9.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Điểm:");

        jLabel10.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("+ Quá trình: ");

        txQT.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txQT.setForeground(new java.awt.Color(255, 255, 51));

        jLabel12.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("+ Giữa kỳ:  ");

        txGK.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txGK.setForeground(new java.awt.Color(255, 255, 51));

        jLabel14.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("+ Cuối kỳ:  ");

        txCK.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txCK.setForeground(new java.awt.Color(255, 255, 51));

        jLabel16.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setText("+ Học phần: ");

        txHP.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        txHP.setForeground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txTen)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(txMSSV)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)
                        .addGap(0, 0, 0)
                        .addComponent(txLop)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(txQT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(txGK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(txCK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(txHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(637, 637, 637)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txTen)
                    .addComponent(jLabel6)
                    .addComponent(txMSSV)
                    .addComponent(jLabel8)
                    .addComponent(txLop))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txQT)
                    .addComponent(jLabel12)
                    .addComponent(txGK)
                    .addComponent(jLabel14)
                    .addComponent(txCK)
                    .addComponent(jLabel16)
                    .addComponent(txHP))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TENMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TENMH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MSSVActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        if (listMon.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn mã lớp học!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Integer.parseInt(MSSV.getText());
                try {
                    diemSinhvien a = new diemSinhvien(MSSV.getText(), MAMH);
                    if (null == a.HOTEN) {
                        JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên " + MSSV.getText() + " trong lớp " + MALOPHOC + " !", "Error!", JOptionPane.ERROR_MESSAGE);
                    } else {
                        txTen.setText(a.HOTEN);
                        txMSSV.setText(a.MSSV);
                        txLop.setText(Giaovien.getLOPSH(a.MSSV));
                        txQT.setText(Float.toString(a.QT));
                        txGK.setText(Float.toString(a.GK));
                        txCK.setText(Float.toString(a.CK));
                        txHP.setText(Float.toString(a.HP));
//                        btXoadiem.setEnabled(true);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Giaovien_Xoa_Sua.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (NumberFormatException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên " + MSSV.getText() + " trong lớp " + MALOPHOC + " !", "Error!", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btSubmitActionPerformed

    private void listMonValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMonValueChanged
        listMon.setSelectionBackground(new java.awt.Color(255, 153, 0));
        listMon.setSelectionForeground(Color.WHITE);
        String b = listMon.getSelectedValue().toString();
        ResultSet timMH;
        try {
            timMH = main.st.executeQuery("select DISTINCT * from LOPHOC , MONHOC where LOPHOC.MAMH = MONHOC.MAMH and MALOPHOC = '" + b + "'");
            if (timMH.next()) {
                TENMH.setText(timMH.getString("TENMH"));
                MAMH = timMH.getString("MAMH");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Giaovien_Xoa_Sua.class.getName()).log(Level.SEVERE, null, ex);
        }
        MALOPHOC = b;

    }//GEN-LAST:event_listMonValueChanged

    private void MSSVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MSSVKeyPressed
        // TODO add your handling code here:
//        btXoadiem.setEnabled(false);
    }//GEN-LAST:event_MSSVKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MSSV;
    private javax.swing.JLabel TENMH;
    private javax.swing.JButton btSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMon;
    private javax.swing.JLabel txCK;
    private javax.swing.JLabel txGK;
    private javax.swing.JLabel txHP;
    private javax.swing.JLabel txLop;
    private javax.swing.JLabel txMSSV;
    private javax.swing.JLabel txQT;
    private javax.swing.JLabel txTen;
    // End of variables declaration//GEN-END:variables
}
