
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class Sinhvien_Xemdiem extends javax.swing.JPanel {

    public static DefaultTableModel model = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        
        
    };

    public Sinhvien_Xemdiem() throws SQLException {
        tb = new javax.swing.JLabel();
        setBackground(new java.awt.Color(0, 51, 51));
        this.setVisible(true);
        this.setSize(Sinhvien.size);
        tb = new javax.swing.JLabel();
        initComponents();
        jTable1.getTableHeader().setFont(new Font("UTM Amerika Sans", Font.BOLD, 18)); // cài đặt kiểu chữ title column
        jTable1.getTableHeader().setBackground(Color.orange); // cài đặt màu title column
        // set căn lề center
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(String.class, centerRenderer);

        while (jTable1.getRowCount() != 0) {
            model.removeRow(0);
        }
        //set kích thước của cột và hàng
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setRowHeight(40);
        addRow();
        tb.setText("Điểm trung bình tích lũy: " + main.tb_HP(main.Maso)+"------------------");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        /*
        jTable1 = new javax.swing.JTable(model);
        tb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        */
        jTable1.setBackground(new java.awt.Color(255,255,255));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setFont(new java.awt.Font("UTM Amerika Sans", 1, 18)); // NOI18N
        /*
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        */
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);

        tb.setFont(new java.awt.Font("UTM Amerika Sans", 1, 24)); // NOI18N
        tb.setForeground(new java.awt.Color(255, 255, 51));
        tb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tb.setText("Chọn lớp học.....");
        tb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(tb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void addRow() throws SQLException {
        String[] list=Sinhvien.getDsLop(main.Maso);
        for (int i = 0; list[i]!=null; i++) {
            diemSinhvien a = new diemSinhvien(main.Maso, list[i]);
            model.addRow(new Object[]{a.MAMH, a.TENMH, a.QT, a.GK, a.CK, a.HP, ""});
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel tb;
    // End of variables declaration//GEN-END:variables
}
