
import sun.security.x509.X500Name;


public class Sv_Monhoc_Xem extends javax.swing.JPanel {

    
    public Sv_Monhoc_Xem(float[] G, int check) {
        initComponents();
        if(G[0]!=-1){
            slG1.setValue(Math.round(G[0]));
            soG1.setText(Float.toString(Math.round(G[0]))+"%");
        }else pnG1.setVisible(false);
        if(G[1]!=-1){
            slG2.setValue(Math.round(G[1]));
            soG2.setText(Float.toString(Math.round(G[1]))+"%");
        }else pnG2.setVisible(false);
        if(G[2]!=-1){
            slG3.setValue(Math.round(G[2]));
            soG3.setText(Float.toString(Math.round(G[2]))+"%");
        }else pnG3.setVisible(false);
        if(G[3]!=-1){
            slG4.setValue(Math.round(G[3]));
            soG4.setText(Float.toString(Math.round(G[3]))+"%");
        }else pnG4.setVisible(false);
        if(G[4]!=-1){
            slG5.setValue(Math.round(G[4]));
            soG5.setText(Float.toString(Math.round(G[4]))+"%");
        }else pnG5.setVisible(false);
        
        if (check==1) 
            title.setText("Chuẩn đánh giá: GIỮA KỲ");
        if (check==2) 
            title.setText("Chuẩn đánh giá: CUỐI KỲ");
        if (check==3) 
            title.setText("Kết quả chuẩn đầu ra môn học:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnG1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        slG1 = new javax.swing.JSlider();
        soG1 = new javax.swing.JLabel();
        pnG2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        slG2 = new javax.swing.JSlider();
        soG2 = new javax.swing.JLabel();
        pnG3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        slG3 = new javax.swing.JSlider();
        soG3 = new javax.swing.JLabel();
        pnG4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        slG4 = new javax.swing.JSlider();
        soG4 = new javax.swing.JLabel();
        pnG5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        slG5 = new javax.swing.JSlider();
        soG5 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        pnG1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("UTM Amerika Sans", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Chuẩn G1");

        slG1.setBackground(new java.awt.Color(0, 51, 51));
        slG1.setForeground(new java.awt.Color(255, 51, 51));
        slG1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        slG1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        slG1.setEnabled(false);
        slG1.setMaximumSize(new java.awt.Dimension(32767, 31));
        slG1.setMinimumSize(new java.awt.Dimension(36, 31));

        soG1.setFont(new java.awt.Font("UTM Amerika Sans", 1, 20)); // NOI18N
        soG1.setForeground(new java.awt.Color(255, 255, 0));
        soG1.setText("50%");

        javax.swing.GroupLayout pnG1Layout = new javax.swing.GroupLayout(pnG1);
        pnG1.setLayout(pnG1Layout);
        pnG1Layout.setHorizontalGroup(
            pnG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(slG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(soG1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnG1Layout.setVerticalGroup(
            pnG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG1Layout.createSequentialGroup()
                .addGroup(pnG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soG1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnG1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnG2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel13.setFont(new java.awt.Font("UTM Amerika Sans", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Chuẩn G2");

        slG2.setBackground(new java.awt.Color(0, 51, 51));
        slG2.setForeground(new java.awt.Color(255, 51, 51));
        slG2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        slG2.setEnabled(false);

        soG2.setFont(new java.awt.Font("UTM Amerika Sans", 1, 20)); // NOI18N
        soG2.setForeground(new java.awt.Color(255, 255, 0));
        soG2.setText("50%");

        javax.swing.GroupLayout pnG2Layout = new javax.swing.GroupLayout(pnG2);
        pnG2.setLayout(pnG2Layout);
        pnG2Layout.setHorizontalGroup(
            pnG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(slG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(soG2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnG2Layout.setVerticalGroup(
            pnG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG2Layout.createSequentialGroup()
                .addGroup(pnG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soG2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnG2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnG3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel15.setFont(new java.awt.Font("UTM Amerika Sans", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("Chuẩn G3");

        slG3.setBackground(new java.awt.Color(0, 51, 51));
        slG3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        slG3.setEnabled(false);

        soG3.setFont(new java.awt.Font("UTM Amerika Sans", 1, 20)); // NOI18N
        soG3.setForeground(new java.awt.Color(255, 255, 0));
        soG3.setText("50%");

        javax.swing.GroupLayout pnG3Layout = new javax.swing.GroupLayout(pnG3);
        pnG3.setLayout(pnG3Layout);
        pnG3Layout.setHorizontalGroup(
            pnG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(slG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(soG3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnG3Layout.setVerticalGroup(
            pnG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG3Layout.createSequentialGroup()
                .addGroup(pnG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soG3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnG3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnG4.setBackground(new java.awt.Color(0, 51, 51));

        jLabel17.setFont(new java.awt.Font("UTM Amerika Sans", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("Chuẩn G4");

        slG4.setBackground(new java.awt.Color(0, 51, 51));
        slG4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        slG4.setEnabled(false);

        soG4.setFont(new java.awt.Font("UTM Amerika Sans", 1, 20)); // NOI18N
        soG4.setForeground(new java.awt.Color(255, 255, 0));
        soG4.setText("50%");

        javax.swing.GroupLayout pnG4Layout = new javax.swing.GroupLayout(pnG4);
        pnG4.setLayout(pnG4Layout);
        pnG4Layout.setHorizontalGroup(
            pnG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(slG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(soG4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnG4Layout.setVerticalGroup(
            pnG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG4Layout.createSequentialGroup()
                .addGroup(pnG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soG4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnG4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slG4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnG5.setBackground(new java.awt.Color(0, 51, 51));

        jLabel19.setFont(new java.awt.Font("UTM Amerika Sans", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 0));
        jLabel19.setText("Chuẩn G5");

        slG5.setBackground(new java.awt.Color(0, 51, 51));
        slG5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        slG5.setEnabled(false);

        soG5.setFont(new java.awt.Font("UTM Amerika Sans", 1, 20)); // NOI18N
        soG5.setForeground(new java.awt.Color(255, 255, 0));
        soG5.setText("50%");

        javax.swing.GroupLayout pnG5Layout = new javax.swing.GroupLayout(pnG5);
        pnG5.setLayout(pnG5Layout);
        pnG5Layout.setHorizontalGroup(
            pnG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(slG5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(soG5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnG5Layout.setVerticalGroup(
            pnG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnG5Layout.createSequentialGroup()
                .addGroup(pnG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soG5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnG5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slG5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        title.setFont(new java.awt.Font("UTM Amerika Sans", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 0));
        title.setText("Chuẩn đầu ra môn học: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnG4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnG5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pnG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnG5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel pnG1;
    private javax.swing.JPanel pnG2;
    private javax.swing.JPanel pnG3;
    private javax.swing.JPanel pnG4;
    private javax.swing.JPanel pnG5;
    private javax.swing.JSlider slG1;
    private javax.swing.JSlider slG2;
    private javax.swing.JSlider slG3;
    private javax.swing.JSlider slG4;
    private javax.swing.JSlider slG5;
    private javax.swing.JLabel soG1;
    private javax.swing.JLabel soG2;
    private javax.swing.JLabel soG3;
    private javax.swing.JLabel soG4;
    private javax.swing.JLabel soG5;
    public static javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
